### PR TITLE
Wireplumber 0.4.16

### PR DESCRIPTION
**Pull request by mmstick**

### CODE REVIEW

**Comment by pojunen** [comment]
There is now 0.4.16 version, from it's changelog looks like atleast PipeWire 0.3.68 is required (which is not problem on Pop!_OS):

https://salsa.debian.org/utopia-team/wireplumber/-/commit/0d5acf2c7e833c58c3b771d655e36eb7831133e5

https://gitlab.freedesktop.org/pipewire/wireplumber/-/releases/0.4.16

**Comment by mmstick** [comment]
@pojunen This is 0.4.16. I set the wrong title for the PR.

**Review by jacobgkau — APPROVED** [review]
Tested with https://github.com/pop-os/pipewire/pull/68.

**Review by jackpot51 — APPROVED** [review]

**Comment by pojunen** [comment]
https://gitlab.freedesktop.org/pipewire/wireplumber/-/releases/0.4.17

Small hotfix for 0.4.16 regressions.

Fixed a reference counting issue in the object managers that could cause
crashes due to memory corruption

Fixed an issue with filters linking to wrong targets, often with two sets
of links

Fixed a crash in the endpoints policy that would show up when log messages
were enabled at level 3 or higher

**Pull request merged**
